/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class my_play_UDFs */

#ifndef _Included_my_play_UDFs
#define _Included_my_play_UDFs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     my_play_UDFs
 * Method:    runMapping
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_my_play_UDFs_runMapping
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     my_play_UDFs
 * Method:    run
 * Signature: (Lmy/play/KafkaMessage;)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_my_play_UDFs_run
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
